FROM openjdk:8-alpine
  
WORKDIR /transport-service
ADD target/*.jar .

COPY autostart-qa.sh /root/autostart-qa.sh
RUN chmod 755 /root/autostart-qa.sh
RUN apk add curl

ENTRYPOINT ["/root/autostart-qa.sh"]