FROM openjdk:8-alpine
  
WORKDIR /parking-lot
ADD app-parking-lot/target/*.jar .

COPY autostart-prod.sh /root/autostart-prod.sh
RUN chmod 755 /root/autostart-prod.sh
RUN apk add curl

ENTRYPOINT ["/root/autostart-prod.sh"]