FROM openjdk:8-alpine
  
WORKDIR /parking-lot
ADD app-parking-lot/target/*.jar .

COPY autostart-dev.sh /root/autostart-dev.sh
RUN chmod 755 /root/autostart-dev.sh
RUN apk add curl

ENTRYPOINT ["/root/autostart-dev.sh"]